<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TaskMind.Application.Commons\TaskMind.Applications.Commons.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Handlers\Companies\" />
    <Folder Include="Handlers\Dashbroads\" />
    <Folder Include="Handlers\Invoices\" />
    <Folder Include="Handlers\Skills\" />
    <Folder Include="Handlers\Users\" />
    <Folder Include="Requests\Companies\" />
    <Folder Include="Requests\Dashbroads\" />
    <Folder Include="Requests\Invoices\" />
    <Folder Include="Requests\Skills\" />
  </ItemGroup>

</Project>
