<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TaskMind.Domain.Commons\TaskMind.Domain.Commons.csproj" />
    <ProjectReference Include="..\TaskMind.Domain.Events\TaskMind.Domain.Events.csproj" />
  </ItemGroup>

</Project>
