<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Features\Finds\**" />
    <EmbeddedResource Remove="Features\Finds\**" />
    <None Remove="Features\Finds\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Commons\" />
    <Folder Include="Features\Projects\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TaskMind.Application.Commons\TaskMind.Applications.Commons.csproj" />
  </ItemGroup>

</Project>
